<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-03-14 05:47
=======
# Generated by Django 4.1.7 on 2023-03-06 01:19
>>>>>>> b90613e8ab3811348bf34a27e57a3f3b724c9d1f

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=places.models.upload_load),
        ),
    ]
